### ISSUE TITLE
Inputbox component

### ISSUE THREAD

**Issue by Sasikuttan2163** [lugvitc/c0d-frontend#1]
**NOTE:** Use storybook to preview your component. Ideally do not create pages to test your component. If you do make on, remember to delete the page before pushing. Refer `src/components/text.tsx` and `src/stories/text.stories.tsx` for examples

Create inputbox component which takes the hint as parameter. Extend HTMLInputElement. Password box will need type set to password. Check src/components/Text.tsx for example implementation.

Ref:
![image](https://github.com/user-attachments/assets/072645d5-7043-4a83-9eea-985623251a0b)
![image](https://github.com/user-attachments/assets/fb2c5b89-e5ec-4484-b1fa-7ecaf05cf432)

**Comment by Dreamgamer5000** [comment]
I can take up this.

**Comment by ThEditor** [comment]
Solved
