### ISSUE TITLE
Leaderboard entry component

### ISSUE THREAD

**Issue by Sasikuttan2163** [lugvitc/c0d-frontend#10]
## Description
Create leaderboard entry component to be shown in the leaderboards page, transparent on hover.
![image](https://github.com/user-attachments/assets/0100bd41-b457-4cce-9b5c-8c5da2f8f881)

NOTE: Use **storybook** to preview your component. Ideally **do not create pages** to test your component. If you do make on, remember to **delete the page before pushing**. Refer src/components/text.tsx and src/stories/text.stories.tsx for examples.

### Reference
![image](https://github.com/user-attachments/assets/b75dac4e-68ad-447f-b5e4-b7f6dd3ef336)

### Variants
Leaderboard header
![image](https://github.com/user-attachments/assets/3575ea20-7b2b-491c-bee5-dc15d809d7d7)

**Comment by Dreamgamer5000** [comment]
i shall work on this tonight
