### ISSUE TITLE
Sign up form

### ISSUE THREAD

**Issue by Sasikuttan2163** [lugvitc/c0d-frontend#15]
## Description

Bunch together Inputboxes, Text and buttons to build the sign up component. Use LinkButton component for the "Sign In" part in the "Already have an ..." text.

Code must be in components/signup/signup-form.tsx

![image](https://github.com/user-attachments/assets/a12778b3-8cea-43dc-b099-156b60097dfd)

NOTE: Use **storybook** to preview your component. Ideally **do not create pages** to test your component. If you do make on, remember to **delete the page before pushing**. Refer src/components/text.tsx and src/stories/text.stories.tsx for examples.

### Reference

![image](https://github.com/user-attachments/assets/b8d8fe2f-7cce-47f5-a1b8-20da41a316af)

**Comment by Dreamgamer5000** [comment]
I can work on this

**Comment by Sasikuttan2163** [comment]
Assigned
