### ISSUE TITLE
Create Team form

### ISSUE THREAD

**Issue by Sasikuttan2163** [lugvitc/c0d-frontend#17]
## Description
Bunch together Inputboxes, Text and buttons to build the create team form. On clicking Add Member, two inputboxes pop up to enter name and registration number of Member 1. Then member 2. On having three members including the team leader, the button is hidden.

Code must be in components/create-team/create-team-form.tsx

NOTE: Use **storybook** to preview your component. Ideally **do not create pages** to test your component. If you do make on, remember to **delete the page before pushing**. Refer src/components/text.tsx and src/stories/text.stories.tsx for examples.

![image](https://github.com/user-attachments/assets/f50e0632-8f40-4618-864f-a1f0e7b84dd7)

### Reference

![image](https://github.com/user-attachments/assets/b314f143-9236-4ef1-973d-2f2c0f01fc5e)

**Comment by Dreamgamer5000** [comment]
I would like to work on this as well

**Comment by Dreamgamer5000** [comment]
also what should be the name of the branch be, should it be same as feature/create-team-form

**Comment by Sasikuttan2163** [comment]
yup that works

**Comment by Dreamgamer5000** [comment]
drop this for me, it might extend over 5:30
