### ISSUE TITLE
Challenge page

### ISSUE THREAD

**Issue by Sasikuttan2163** [lugvitc/c0d-frontend#19]
## Description
Challenge page, uses IconButton for back

NOTE: Use **storybook** to preview your component. Ideally **do not create pages** to test your component. If you do make on, remember to **delete the page before pushing**. Refer src/components/text.tsx and src/stories/text.stories.tsx for examples.

### Reference

![image](https://github.com/user-attachments/assets/2878aece-c14b-4408-bb25-8a3350d24195)

**Comment by OneRandom1509** [comment]
i can take up this

**Comment by Sasikuttan2163** [comment]
Assigned
