### ISSUE TITLE
Button component

### ISSUE THREAD

**Issue by ThEditor** [lugvitc/c0d-frontend#2]
**NOTE:** Use storybook to preview your component. Ideally do not create pages to test your component. If you do make on, remember to delete the page before pushing. Refer `src/components/text.tsx` and `src/stories/text.stories.tsx` for examples

## Variants
The button component will have the following variants:

### Primary
`primary`
Create red primary button, turns white on hover.
![image](https://github.com/user-attachments/assets/2e6322fa-cc41-42a2-861f-58c5dbfd515c)

### Secondary
`secondary`
Create white secondary buttons, glow on hover
![image](https://github.com/user-attachments/assets/e1c63c79-ad5a-4797-9b4a-a6300fd3206f)

### Tertiary
`teritary`
Create greyish secondary button, slight brightness increase on hover
![image](https://github.com/user-attachments/assets/b643adc3-24e5-4622-8d30-eac47d3c95d6)

#### Primary
`ghost-primary`
![image](https://github.com/user-attachments/assets/a7dbdf1b-5677-47c2-a7cf-b3e316b03f9f)

#### Secondary
`ghost-secondary`
![image](https://github.com/user-attachments/assets/7f855cf0-4567-4fad-a08c-ba56107bcb1a)

**Comment by OneRandom1509** [comment]
I'd like to take up this issue ^^
