### ISSUE TITLE
Topbar Navlinks component

### ISSUE THREAD

**Issue by Sasikuttan2163** [lugvitc/c0d-frontend#3]
## Description
Create topbar buttons for navigation. Sign In is replaced with "Log Out" if user is logged in.
![image](https://github.com/user-attachments/assets/99e4d285-dc78-413e-93c2-bb143a6d7e5f)

NOTE: Use **storybook** to preview your component. Ideally **do not create pages** to test your component. If you do make on, remember to **delete the page before pushing**. Refer src/components/text.tsx and src/stories/text.stories.tsx for examples.

### Variants
Primary
`ghost-primary`
![image](https://github.com/user-attachments/assets/ff71adf3-04b3-4bd6-800d-2e847d1870eb)
Secondary
`ghost-secondary`
![image](https://github.com/user-attachments/assets/ec5b3a3e-6c9a-4bec-ab8b-ca7bbad8dce3)

**Comment by OneRandom1509** [comment]
Same as #7

**Comment by ThEditor** [comment]
Same as #7
