### ISSUE TITLE
IconButton component

### ISSUE THREAD

**Issue by Sasikuttan2163** [lugvitc/c0d-frontend#5]
## Description
Create clickable icon component for going to previous page. Icon must be a parameter.

![image](https://github.com/user-attachments/assets/32e2f2eb-6ced-42d5-8d10-bec743983be0)

### Reference
![image](https://github.com/user-attachments/assets/564fcfd1-0f8e-4b51-8967-edd8658bc071)

NOTE: Use **storybook** to preview your component. Ideally **do not create pages** to test your component. If you do make on, remember to **delete the page before pushing**. Refer src/components/text.tsx and src/stories/text.stories.tsx for examples.

**Comment by OneRandom1509** [comment]
I'll take up on this issue! ^_^
